server:
  port: ${PORT:3030}
  servlet:
    application-display-name: microservice-java-gateway

logging:
  level:
    root: info

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:3031}/eureka/
    registerWithEureka: false
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

spring:
  application: 
    name: microservice-java-gateway

ribbon:
  eureka:
    enabled: true

zuul:
  prefix: /api
